# Generated by Django 6.0.6 on 2026-06-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transactionsplit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='balance',
        ),
        migrations.CreateModel(
            name='BucketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('memo', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.bucket')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
