# Generated by Django 6.0.6 on 2026-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_bucket_balance_bucketentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('imported_simplefin', 'Imported (SimpleFIN)'), ('imported_qif', 'Imported (QIF history)'), ('imported_csv', 'Imported (CSV history)')], default='manual', max_length=20),
        ),
    ]
