# Generated by Django 6.0.6 on 2026-06-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('money_market', 'Money Market'), ('cash', 'Cash / HYSA'), ('credit_card', 'Credit Card'), ('brokerage', 'Brokerage'), ('401k', '401(k)'), ('ira', 'IRA'), ('hsa', 'HSA'), ('pension', 'Pension'), ('property', 'Property'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('memo', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_entries', to='tracker.account')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
