# Generated by Django 6.0.6 on 2026-06-28 13:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_transaction_is_new_alter_account_type_propertyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='online_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='bucketentry',
            name='txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('imported_simplefin', 'Imported (SimpleFIN)'), ('imported_qif', 'Imported (QIF history)'), ('imported_csv', 'Imported (CSV history)'), ('bucket_transfer', 'Bucket transfer')], default='manual', max_length=20),
        ),
    ]
