# Generated by Django 6.0.6 on 2026-06-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_account_online_balance_bucketentry_txn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
