# Generated by Django 6.0.6 on 2026-06-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_account_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='manual_balance',
            field=models.BooleanField(default=False),
        ),
    ]
