# Generated by Django 6.0.6 on 2026-06-30 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_account_manual_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='in_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_treatment',
            field=models.CharField(blank=True, choices=[('pre_tax', 'Pre-Tax'), ('roth', 'Roth'), ('pension', 'Pension'), ('taxable', 'Taxable'), ('hsa', 'HSA'), ('cash', 'Cash')], max_length=10),
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='tracker.account')),
            ],
            options={
                'ordering': ['-snapshot_date', 'account__name'],
                'unique_together': {('account', 'snapshot_date')},
            },
        ),
    ]
