# Generated by Django 6.0.6 on 2026-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_account_in_portfolio_account_tax_treatment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
