# Generated by Django 6.0.6 on 2026-07-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_networthsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('question', models.TextField()),
                ('reply', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('rounds', models.IntegerField(default=0)),
                ('tool_calls', models.JSONField(default=list)),
                ('duration_ms', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
