# Generated by Django 6.0.6 on 2026-07-04 11:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_agentcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.CreateModel(
            name='PayeeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(db_index=True, max_length=200)),
                ('local_payee', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee_aliases', to='tracker.account')),
            ],
            options={
                'ordering': ['bank_name'],
                'constraints': [models.UniqueConstraint(fields=('bank_name', 'local_payee'), name='uniq_payee_alias')],
            },
        ),
    ]
