# Generated by Django 6.0.6 on 2026-07-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_backfill_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exclude_match',
            field=models.BooleanField(default=False),
        ),
    ]
