# Generated by Django 6.0.6 on 2026-07-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_transaction_exclude_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('bucket', 'Bucket set-aside'), ('transfer', 'Account transfer'), ('payment', 'Payment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('day', models.IntegerField(default=20)),
                ('month_offset', models.IntegerField(default=0)),
                ('payee', models.CharField(blank=True, max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('last_posted', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled', to='tracker.category')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='tracker.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_in', to='tracker.account')),
                ('to_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled', to='tracker.bucket')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
